version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    build: ./.docker/php
    environment:
      MARIADB_HOST: mariadb
      MARIADB_USER: ${PLF_LOWP_USER}
      MARIADB_PASSWORD: ${PLF_LOWP_USER_PASSWORD}
      MARIADB_DATABASE: ${PLF_DATABASE}
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    depends_on:
      - mariadb

  #MariaDb Service
  mariadb:
    image: bitnami/mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${PLF_MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${PLF_LOWP_USER}
      MARIADB_PASSWORD: ${PLF_LOWP_USER_PASSWORD}
      MARIADB_DATABASE: ${PLF_DATABASE}
      MARIADB_PORT_NUMBER: 3306
    volumes:
      - ./.docker/mariadb/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf
      - ./.docker/mariadb/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadata:/bitnami/mariadb/data

# Volumes
volumes:
  mariadata:

